login_check:
    pattern:   /admin/login_check
    options:
      i18n: false

admin_logout:
    pattern:   /admin/logout
    options:
      i18n: false

_imagine:
    resource: .
    type:     imagine

s_estruch_website:
    resource: "@SEstruchWebsiteBundle/Controller/"
    type:     annotation
    prefix:   /


# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
